name: Build & Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image
        run: |
          docker build -t zafarrashid/my-website:${{ github.sha }} .
          docker push zafarrashid/my-website:${{ github.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Helm Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
            | helm registry login --username AWS --password-stdin 414927534660.dkr.ecr.us-east-1.amazonaws.com

      - name: Package & Push Helm Chart
        run: |
          helm package ./my-website
          helm push my-website-*.tgz oci://414927534660.dkr.ecr.us-east-1.amazonaws.com/helm
